version: '3'
services:

  bzkflow:
    build:
        context: ./bzk/
        dockerfile: bzkflow/Dockerfile
    ports: 
      - "9202:8080"
    depends_on:
      - "db" 
  editor-web:
    build: ./flow-editor
    ports: 
      - "9280:80"   
  db:
    image: postgres
    environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=root
    ports: 
      - "5432:5432"
  
        
        
        
        
