version: '3'
services:

  bzkflow:
    image: net.bzk/bzkflow
    ports: 
      - "9202:8080"
  flow-gists:
    image: net.bzk/flow-gists
    ports: 
      - "9203:8081"     
  editor-web:
    build: ./flow-editor
    ports: 
      - "9280:80"   
  db:
    image: postgres
    environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=root
    ports: 
      - "5432:5432"
  
        
        
        
        
