version: '2'
services:

  bzkflow:
    image: net.bzk/bzkflow
    ports: 
      - "9202:8080"
  flow-gists:
    image: net.bzk/flow-gists
    ports: 
      - "9203:8081"     
  editor-web:
    build: ./flow-editor
    ports: 
      - "9280:80"           
  
        
        
        
        
