version: '3'
services:

  bzkflow:
    build:
        context: ./bzk/
        dockerfile: bzkflow/Dockerfile
    ports: 
      - "9202:8080"
    depends_on:
      - "db"
      - "mongodb"      
  editor-web:
    build: ./flow-editor
    ports: 
      - "9280:80"   
  db:
    image: postgres
    environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=root
    ports: 
      - "5432:5432"
  mongodb:
    image: mongo:4.1.13
    environment:
       - MONGO_INITDB_ROOT_USERNAME=root
       - MONGO_INITDB_ROOT_PASSWORD=root
       - MONGO_INITDB_DATABASE=bzklog       
    ports: 
      - "27017:27017"   
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 3096M    
   
  
        
        
        
        
