export class TimeZoneIds {

  public static timeZones = [
    { timeShift: '	-12:00	 ', id: 'Etc/GMT+12', loc: '		  ' },
    { timeShift: '	-11:00	 ', id: 'Etc/GMT+11', loc: '		  ' },
    { timeShift: '	-11:00	 ', id: 'Pacific/Apia', loc: '		  ' },
    { timeShift: '	-11:00	 ', id: 'Pacific/Midway', loc: '		  ' },
    { timeShift: '	-11:00	 ', id: 'Pacific/Niue', loc: '		  ' },
    { timeShift: '	-11:00	 ', id: 'Pacific/Pago_Pago', loc: '	Pacific/Samoa, US/Samoa	  ' },
    { timeShift: '	-10:00	 ', id: 'America/Adak', loc: '	America/Atka, US/Aleutian	  ' },
    { timeShift: '	-10:00	 ', id: 'Etc/GMT+10', loc: '		  ' },
    { timeShift: '	-10:00	 ', id: 'HST', loc: '		  ' },
    { timeShift: '	-10:00	 ', id: 'Pacific/Fakaofo', loc: '		  ' },
    { timeShift: '	-10:00	 ', id: 'Pacific/Honolulu', loc: '	US/Hawaii	  ' },
    { timeShift: '	-10:00	 ', id: 'Pacific/Johnston', loc: '		  ' },
    { timeShift: '	-10:00	 ', id: 'Pacific/Rarotonga', loc: '		  ' },
    { timeShift: '	-10:00	 ', id: 'Pacific/Tahiti', loc: '		  ' },
    { timeShift: '	-09:30	 ', id: 'Pacific/Marquesas', loc: '		  ' },
    { timeShift: '	-09:00	 ', id: 'America/Anchorage', loc: '	US/Alaska	  ' },
    { timeShift: '	-09:00	 ', id: 'America/Juneau', loc: '		  ' },
    { timeShift: '	-09:00	 ', id: 'America/Nome', loc: '		  ' },
    { timeShift: '	-09:00	 ', id: 'America/Yakutat', loc: '		  ' },
    { timeShift: '	-09:00	 ', id: 'Etc/GMT+9', loc: '		  ' },
    { timeShift: '	-09:00	 ', id: 'Pacific/Gambier', loc: '		  ' },
    { timeShift: '	-08:00	 ', id: 'America/Dawson', loc: '		  ' },
    { timeShift: '	-08:00	 ', id: 'America/Los_Angeles', loc: '	US/Pacific, US/Pacific-New	  ' },
    { timeShift: '	-08:00	 ', id: 'America/Santa_Isabel', loc: '		  ' },
    { timeShift: '	-08:00	 ', id: 'America/Tijuana', loc: '	America/Ensenada, Mexico/BajaNorte	  ' },
    { timeShift: '	-08:00	 ', id: 'America/Vancouver', loc: '	Canada/Pacific	  ' },
    { timeShift: '	-08:00	 ', id: 'America/Whitehorse', loc: '	Canada/Yukon	  ' },
    { timeShift: '	-08:00	 ', id: 'Etc/GMT+8', loc: '		  ' },
    { timeShift: '	-08:00	 ', id: 'PST8PDT', loc: '		  ' },
    { timeShift: '	-08:00	 ', id: 'Pacific/Pitcairn', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Boise', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Cambridge_Bay', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Chihuahua', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Dawson_Creek', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Denver', loc: '	America/Shiprock, Navajo, US/Mountain	  ' },
    { timeShift: '	-07:00	 ', id: 'America/Edmonton', loc: '	Canada/Mountain	  ' },
    { timeShift: '	-07:00	 ', id: 'America/Hermosillo', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Inuvik', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Mazatlan', loc: '	Mexico/BajaSur	  ' },
    { timeShift: '	-07:00	 ', id: 'America/Ojinaga', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'America/Phoenix', loc: '	US/Arizona	  ' },
    { timeShift: '	-07:00	 ', id: 'America/Yellowknife', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'Etc/GMT+7', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'MST', loc: '		  ' },
    { timeShift: '	-07:00	 ', id: 'MST7MDT', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Bahia_Banderas', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Belize', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Cancun', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Chicago', loc: '	US/Central	  ' },
    { timeShift: '	-06:00	 ', id: 'America/Costa_Rica', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/El_Salvador', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Guatemala', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Indiana/Knox', loc: '	America/Knox_IN, US/Indiana-Starke	  ' },
    { timeShift: '	-06:00	 ', id: 'America/Indiana/Tell_City', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Managua', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Matamoros', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Menominee', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Merida', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Mexico_City', loc: '	Mexico/General	  ' },
    { timeShift: '	-06:00	 ', id: 'America/Monterrey', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/North_Dakota/Center', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/North_Dakota/New_Salem', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Rainy_River', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Rankin_Inlet', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Regina', loc: '	Canada/East-Saskatchewan, Canada/Saskatchewan	  ' },
    { timeShift: '	-06:00	 ', id: 'America/Swift_Current', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Tegucigalpa', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'America/Winnipeg', loc: '	Canada/Central	  ' },
    { timeShift: '	-06:00	 ', id: 'CST6CDT', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'Etc/GMT+6', loc: '		  ' },
    { timeShift: '	-06:00	 ', id: 'Pacific/Easter', loc: '	Chile/EasterIsland	  ' },
    { timeShift: '	-06:00	 ', id: 'Pacific/Galapagos', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Atikokan', loc: '	America/Coral_Harbour	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Bogota', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Cayman', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Detroit', loc: '	US/Michigan	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Grand_Turk', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Guayaquil', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Havana', loc: '	Cuba	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Indianapolis', loc: '	America/Fort_Wayne, America/Indianapolis, US/East-Indiana	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Marengo', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Petersburg', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Vevay', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Vincennes', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Indiana/Winamac', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Iqaluit', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Jamaica', loc: '	Jamaica	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Kentucky/Louisville', loc: '	America/Louisville	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Kentucky/Monticello', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Lima', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Montreal', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Nassau', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/New_York', loc: '	US/Eastern	  ' },
    { timeShift: '	-05:00	 ', id: 'America/Nipigon', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Panama', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Pangnirtung', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Port-au-Prince', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Resolute', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Thunder_Bay', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'America/Toronto', loc: '	Canada/Eastern	  ' },
    { timeShift: '	-05:00	 ', id: 'EST', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'EST5EDT', loc: '		  ' },
    { timeShift: '	-05:00	 ', id: 'Etc/GMT+5', loc: '		  ' },
    { timeShift: '	-04:30	 ', id: 'America/Caracas', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Anguilla', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Antigua', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/San_Luis', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Aruba', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Asuncion', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Barbados', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Blanc-Sablon', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Boa_Vista', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Campo_Grande', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Cuiaba', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Curacao', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Dominica', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Eirunepe', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Glace_Bay', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Goose_Bay', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Grenada', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Guadeloupe', loc: '	America/Marigot, America/St_Barthelemy	  ' },
    { timeShift: '	-04:00	 ', id: 'America/Guyana', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Halifax', loc: '	Canada/Atlantic	  ' },
    { timeShift: '	-04:00	 ', id: 'America/La_Paz', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Manaus', loc: '	Brazil/West	  ' },
    { timeShift: '	-04:00	 ', id: 'America/Martinique', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Moncton', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Montserrat', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Port_of_Spain', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Porto_Velho', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Puerto_Rico', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Rio_Branco', loc: '	America/Porto_Acre, Brazil/Acre	  ' },
    { timeShift: '	-04:00	 ', id: 'America/Santiago', loc: '	Chile/Continental	  ' },
    { timeShift: '	-04:00	 ', id: 'America/Santo_Domingo', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/St_Kitts', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/St_Lucia', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/St_Thomas', loc: '	America/Virgin	  ' },
    { timeShift: '	-04:00	 ', id: 'America/St_Vincent', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Thule', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'America/Tortola', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'Antarctica/Palmer', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'Atlantic/Bermuda', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'Atlantic/Stanley', loc: '		  ' },
    { timeShift: '	-04:00	 ', id: 'Etc/GMT+4', loc: '		  ' },
    { timeShift: '	-03:30	 ', id: 'America/St_Johns', loc: '	Canada/Newfoundland	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Araguaina', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Buenos_Aires', loc: '	America/Buenos_Aires	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Catamarca', loc: '	America/Argentina/ComodRivadavia, America/Catamarca	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Cordoba', loc: '	America/Cordoba, America/Rosario	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Jujuy', loc: '	America/Jujuy	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/La_Rioja', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Mendoza', loc: '	America/Mendoza	  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Rio_Gallegos', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Salta', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/San_Juan', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Tucuman', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Argentina/Ushuaia', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Bahia', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Belem', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Cayenne', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Fortaleza', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Godthab', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Maceio', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Miquelon', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Montevideo', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Paramaribo', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Recife', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Santarem', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'America/Sao_Paulo', loc: '	Brazil/East	  ' },
    { timeShift: '	-03:00	 ', id: 'Antarctica/Rothera', loc: '		  ' },
    { timeShift: '	-03:00	 ', id: 'Etc/GMT+3', loc: '		  ' },
    { timeShift: '	-02:00	 ', id: 'America/Noronha', loc: '	Brazil/DeNoronha	  ' },
    { timeShift: '	-02:00	 ', id: 'Atlantic/South_Georgia', loc: '		  ' },
    { timeShift: '	-02:00	 ', id: 'Etc/GMT+2', loc: '		  ' },
    { timeShift: '	-01:00	 ', id: 'America/Scoresbysund', loc: '		  ' },
    { timeShift: '	-01:00	 ', id: 'Atlantic/Azores', loc: '		  ' },
    { timeShift: '	-01:00	 ', id: 'Atlantic/Cape_Verde', loc: '		  ' },
    { timeShift: '	-01:00	 ', id: 'Etc/GMT+1', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Abidjan', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Accra', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Bamako', loc: '	Africa/Timbuktu	  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Banjul', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Bissau', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Casablanca', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Conakry', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Dakar', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/El_Aaiun', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Freetown', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Lome', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Monrovia', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Nouakchott', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Ouagadougou', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Africa/Sao_Tome', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'America/Danmarkshavn', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Atlantic/Canary', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Atlantic/Faroe', loc: '	Atlantic/Faeroe	  ' },
    { timeShift: '	+00:00	 ', id: 'Atlantic/Madeira', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Atlantic/Reykjavik', loc: '	Iceland	  ' },
    { timeShift: '	+00:00	 ', id: 'Atlantic/St_Helena', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'Etc/GMT', loc: '	Etc/GMT+0, Etc/GMT-0, Etc/GMT0, Etc/Greenwich, GMT, GMT+0, GMT-0, GMT0, Greenwich	  ' },
    { timeShift: '	+00:00	 ', id: 'Etc/UCT', loc: '	UCT	  ' },
    { timeShift: '	+00:00	 ', id: 'Etc/UTC', loc: '	Etc/Universal, Etc/Zulu, Universal, Zulu	  ' },
    { timeShift: '	+00:00	 ', id: 'Europe/Dublin', loc: '	Eire	  ' },
    { timeShift: '	+00:00	 ', id: 'Europe/Lisbon', loc: '	Portugal	  ' },
    { timeShift: '	+00:00	 ', id: 'Europe/London', loc: '	Europe/Belfast, Europe/Guernsey, Europe/Isle_of_Man, Europe/Jersey, GB, GB-Eire	  ' },
    { timeShift: '	+00:00	 ', id: 'UTC', loc: '		  ' },
    { timeShift: '	+00:00	 ', id: 'WET', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Algiers', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Bangui', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Brazzaville', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Ceuta', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Douala', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Kinshasa', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Lagos', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Libreville', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Luanda', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Malabo', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Ndjamena', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Niamey', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Porto-Novo', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Tunis', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Africa/Windhoek', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'CET', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Etc/GMT-1', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Amsterdam', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Andorra', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Belgrade', loc: '	Europe/Ljubljana, Europe/Podgorica, Europe/Sarajevo, Europe/Skopje, Europe/Zagreb	  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Berlin', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Brussels', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Budapest', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Copenhagen', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Gibraltar', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Luxembourg', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Madrid', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Malta', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Monaco', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Oslo', loc: '	Arctic/Longyearbyen, Atlantic/Jan_Mayen	  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Paris', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Prague', loc: '	Europe/Bratislava	  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Rome', loc: '	Europe/San_Marino, Europe/Vatican	  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Stockholm', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Tirane', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Vaduz', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Vienna', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Warsaw', loc: '	Poland	  ' },
    { timeShift: '	+01:00	 ', id: 'Europe/Zurich', loc: '		  ' },
    { timeShift: '	+01:00	 ', id: 'MET', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Blantyre', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Bujumbura', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Cairo', loc: '	Egypt	  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Gaborone', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Harare', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Johannesburg', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Kigali', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Lubumbashi', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Lusaka', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Maputo', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Maseru', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Mbabane', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Africa/Tripoli', loc: '	Libya	  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Amman', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Beirut', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Damascus', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Gaza', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Jerusalem', loc: '	Asia/Tel_Aviv, Israel	  ' },
    { timeShift: '	+02:00	 ', id: 'Asia/Nicosia', loc: '	Europe/Nicosia	  ' },
    { timeShift: '	+02:00	 ', id: 'EET', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Etc/GMT-2', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Athens', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Bucharest', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Chisinau', loc: '	Europe/Tiraspol	  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Helsinki', loc: '	Europe/Mariehamn	  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Istanbul', loc: '	Asia/Istanbul, Turkey	  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Kaliningrad', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Kiev', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Minsk', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Riga', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Simferopol', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Sofia', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Tallinn', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Uzhgorod', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Vilnius', loc: '		  ' },
    { timeShift: '	+02:00	 ', id: 'Europe/Zaporozhye', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Addis_Ababa', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Asmara', loc: '	Africa/Asmera	  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Dar_es_Salaam', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Djibouti', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Kampala', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Khartoum', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Mogadishu', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Africa/Nairobi', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Antarctica/Syowa', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Aden', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Baghdad', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Bahrain', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Kuwait', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Qatar', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Asia/Riyadh', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Etc/GMT-3', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Europe/Moscow', loc: '	W-SU	  ' },
    { timeShift: '	+03:00	 ', id: 'Europe/Samara', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Europe/Volgograd', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Indian/Antananarivo', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Indian/Comoro', loc: '		  ' },
    { timeShift: '	+03:00	 ', id: 'Indian/Mayotte', loc: '		  ' },
    { timeShift: '	+03:30	 ', id: 'Asia/Tehran', loc: '	Iran	  ' },
    { timeShift: '	+04:00	 ', id: 'Asia/Baku', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Asia/Dubai', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Asia/Muscat', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Asia/Tbilisi', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Asia/Yerevan', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Etc/GMT-4', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Indian/Mahe', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Indian/Mauritius', loc: '		  ' },
    { timeShift: '	+04:00	 ', id: 'Indian/Reunion', loc: '		  ' },
    { timeShift: '	+04:30	 ', id: 'Asia/Kabul', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Antarctica/Mawson', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Aqtau', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Aqtobe', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Ashgabat', loc: '	Asia/Ashkhabad	  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Dushanbe', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Karachi', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Oral', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Samarkand', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Tashkent', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Asia/Yekaterinburg', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Etc/GMT-5', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Indian/Kerguelen', loc: '		  ' },
    { timeShift: '	+05:00	 ', id: 'Indian/Maldives', loc: '		  ' },
    { timeShift: '	+05:30	 ', id: 'Asia/Colombo', loc: '		  ' },
    { timeShift: '	+05:30	 ', id: 'Asia/Kolkata', loc: '	Asia/Calcutta	  ' },
    { timeShift: '	+05:45	 ', id: 'Asia/Kathmandu', loc: '	Asia/Katmandu	  ' },
    { timeShift: '	+06:00	 ', id: 'Antarctica/Vostok', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Almaty', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Bishkek', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Dhaka', loc: '	Asia/Dacca	  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Novokuznetsk', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Novosibirsk', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Omsk', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Qyzylorda', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Asia/Thimphu', loc: '	Asia/Thimbu	  ' },
    { timeShift: '	+06:00	 ', id: 'Etc/GMT-6', loc: '		  ' },
    { timeShift: '	+06:00	 ', id: 'Indian/Chagos', loc: '		  ' },
    { timeShift: '	+06:30	 ', id: 'Asia/Rangoon', loc: '		  ' },
    { timeShift: '	+06:30	 ', id: 'Indian/Cocos', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Antarctica/Davis', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Bangkok', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Ho_Chi_Minh', loc: '	Asia/Saigon	  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Hovd', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Jakarta', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Krasnoyarsk', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Phnom_Penh', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Pontianak', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Asia/Vientiane', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Etc/GMT-7', loc: '		  ' },
    { timeShift: '	+07:00	 ', id: 'Indian/Christmas', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Antarctica/Casey', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Brunei', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Choibalsan', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Chongqing', loc: '	Asia/Chungking	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Harbin', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Hong_Kong', loc: '	Hongkong	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Irkutsk', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Kashgar', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Kuala_Lumpur', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Kuching', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Macau', loc: '	Asia/Macao	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Makassar', loc: '	Asia/Ujung_Pandang	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Manila', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Shanghai', loc: '	PRC	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Singapore', loc: '	Singapore	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Taipei', loc: '	ROC	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Ulaanbaatar', loc: '	Asia/Ulan_Bator	  ' },
    { timeShift: '	+08:00	 ', id: 'Asia/Urumqi', loc: '		  ' },
    { timeShift: '	+08:00	 ', id: 'Australia/Perth', loc: '	Australia/West	  ' },
    { timeShift: '	+08:00	 ', id: 'Etc/GMT-8', loc: '		  ' },
    { timeShift: '	+08:45	 ', id: 'Australia/Eucla', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Dili', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Jayapura', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Pyongyang', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Seoul', loc: '	ROK	  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Tokyo', loc: '	Japan	  ' },
    { timeShift: '	+09:00	 ', id: 'Asia/Yakutsk', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Etc/GMT-9', loc: '		  ' },
    { timeShift: '	+09:00	 ', id: 'Pacific/Palau', loc: '		  ' },
    { timeShift: '	+09:30	 ', id: 'Australia/Adelaide', loc: '	Australia/South	  ' },
    { timeShift: '	+09:30	 ', id: 'Australia/Broken_Hill', loc: '	Australia/Yancowinna	  ' },
    { timeShift: '	+09:30	 ', id: 'Australia/Darwin', loc: '	Australia/North	  ' },
    { timeShift: '	+10:00	 ', id: 'Antarctica/DumontDUrville', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Asia/Sakhalin', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Asia/Vladivostok', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Brisbane', loc: '	Australia/Queensland	  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Currie', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Hobart', loc: '	Australia/Tasmania	  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Lindeman', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Melbourne', loc: '	Australia/Victoria	  ' },
    { timeShift: '	+10:00	 ', id: 'Australia/Sydney', loc: '	Australia/ACT, Australia/Canberra, Australia/NSW	  ' },
    { timeShift: '	+10:00	 ', id: 'Etc/GMT-10', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Pacific/Chuuk', loc: '	Pacific/Truk, Pacific/Yap	  ' },
    { timeShift: '	+10:00	 ', id: 'Pacific/Guam', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Pacific/Port_Moresby', loc: '		  ' },
    { timeShift: '	+10:00	 ', id: 'Pacific/Saipan', loc: '		  ' },
    { timeShift: '	+10:30	 ', id: 'Australia/Lord_Howe', loc: '	Australia/LHI	  ' },
    { timeShift: '	+11:00	 ', id: 'Antarctica/Macquarie', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Asia/Anadyr', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Asia/Kamchatka', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Asia/Magadan', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Etc/GMT-11', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Pacific/Efate', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Pacific/Guadalcanal', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Pacific/Kosrae', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Pacific/Noumea', loc: '		  ' },
    { timeShift: '	+11:00	 ', id: 'Pacific/Pohnpei', loc: '	Pacific/Ponape	  ' },
    { timeShift: '	+11:30	 ', id: 'Pacific/Norfolk', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Antarctica/McMurdo', loc: '	Antarctica/South_Pole	  ' },
    { timeShift: '	+12:00	 ', id: 'Etc/GMT-12', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Auckland', loc: '	NZ	  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Fiji', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Funafuti', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Kwajalein', loc: '	Kwajalein	  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Majuro', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Nauru', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Tarawa', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Wake', loc: '		  ' },
    { timeShift: '	+12:00	 ', id: 'Pacific/Wallis', loc: '		  ' },
    { timeShift: '	+12:45	 ', id: 'Pacific/Chatham', loc: '	NZ-CHAT	  ' },
    { timeShift: '	+13:00	 ', id: 'Etc/GMT-13', loc: '		  ' },
    { timeShift: '	+13:00	 ', id: 'Pacific/Enderbury', loc: '		  ' },
    { timeShift: '	+13:00	 ', id: 'Pacific/Tongatapu', loc: '		  ' },
    { timeShift: '	+14:00	 ', id: 'Etc/GMT-14', loc: '		  ' },
    { timeShift: '	+14:00	 ', id: 'Pacific/Kiritimati', loc: '		  ' },
  ];

  public static listIds(): Array<string> {
    const ans = new Array<string>();
    for (const tz of TimeZoneIds.timeZones) {
      ans.push(tz.id);
    }
    return ans;
  }

}
